#!/bin/sh
# Build the box3d static library from the vendored submodule into linked-libs/<target>/,
# then probe the public struct layouts the C3 binding pins with $assert.
#
# Usage:
#   scripts/build-box3d.sh            build, then print the probed layouts
#   scripts/build-box3d.sh --check    build, then fail if a layout drifted from scripts/abi-sizes.txt
#   scripts/build-box3d.sh --update   build, then rewrite scripts/abi-sizes.txt from the probe
#
# Cross-compiling the other manifest targets is deferred; this builds the host target only.
set -e

ROOT="$(cd "$(dirname "$0")/.." && pwd)"
VENDOR="$ROOT/vendor/box3d"
TARGET="linux-x64"
OUT="$ROOT/linked-libs/$TARGET"
TYPES="$ROOT/scripts/abi-types.txt"
SIZES="$ROOT/scripts/abi-sizes.txt"
LAYOUT="$ROOT/src/layout.c3"
MODE="${1:-}"

# Emits the C3 compile-time layout pins from the probe output. The C names in abi-sizes.txt are
# converted to their C3 spellings here rather than by hand, which is what makes the correspondence
# between the two sides mechanical instead of something a reader has to verify by eye.
generate_layout() {
    printf '%s\n' "$1" | awk -v types="$TYPES" '
        function to_snake(s,   out, i, c) {
            out = ""
            for (i = 1; i <= length(s); i++) {
                c = substr(s, i, 1)
                if (c ~ /[A-Z]/) {
                    if (i > 1) out = out "_"
                    out = out tolower(c)
                } else {
                    out = out c
                }
            }
            return out
        }
        # An acronym in a C type name folds to one capital: b3AABB is Aabb and b3SATCache is
        # SatCache, because an all-uppercase C3 identifier parses as a constant.
        function to_type(s,   r, out, i, c, prev, after) {
            r = substr(s, 3)
            out = substr(r, 1, 1)
            for (i = 2; i <= length(r); i++) {
                c = substr(r, i, 1)
                prev = substr(r, i - 1, 1)
                after = (i < length(r)) ? substr(r, i + 1, 1) : ""
                if (c ~ /[A-Z]/ && prev ~ /[A-Z]/ && after !~ /[a-z]/) c = tolower(c)
                out = out c
            }
            return out
        }
        # A type whose C3 name the transformation above cannot reach is written `b3X=Y` in
        # abi-types.txt, and Y is used verbatim. b3RecPlayer and its four companions are named for
        # the b3::record module the prefix became, so the transformation would restore the prefix
        # the namespace already carries.
        BEGIN {
            while ((getline line < types) > 0) {
                sub(/#.*/, "", line)
                split(line, part, " ")
                if (part[1] ~ /=/) {
                    split(part[1], nm, "=")
                    override[nm[1]] = nm[2]
                }
            }
            print "module b3;"
            print ""
            print "// Generated by scripts/build-box3d.sh from scripts/abi-sizes.txt. Do not edit."
            print "// Every value here was measured against the real box3d headers; run --update to"
            print "// regenerate and --check to confirm this file still matches the built library."
            print ""
        }
        {
            ctype = $1; size = $2; align = $3
            t = (ctype in override) ? override[ctype] : to_type(ctype)
            print "$assert " t "::size == " size ";"
            print "$assert " t "::alignment == " align ";"
            for (i = 4; i <= NF; i++) {
                split($i, kv, "=")
                idx = i - 4
                if (substr(kv[1], 1, 1) == "@") {
                    printf "$assert %s::members[%d].offset == %s;\n", t, idx, kv[2]
                } else {
                    printf "$assert %s::members[%d].offset == %s && %s::members[%d].name == \"%s\";\n", \
                           t, idx, kv[2], t, idx, to_snake(kv[1])
                }
            }
        }
    '
}

if [ ! -f "$VENDOR/CMakeLists.txt" ]; then
    echo "ERROR: vendor/box3d is empty. Run: git submodule update --init" >&2
    exit 1
fi

# BOX3D_DOUBLE_PRECISION is a PUBLIC compile definition: it switches b3Vec3/b3Pos and every
# struct that embeds them from float to double. The C3 binding is written against the float
# ABI, so it must stay OFF here — a build with it on silently corrupts every call.
echo "Configuring box3d (float ABI, samples/tests/benchmarks off)"
cmake -S "$VENDOR" -B "$VENDOR/build" \
    -DCMAKE_BUILD_TYPE=Release \
    -DCMAKE_POSITION_INDEPENDENT_CODE=ON \
    -DBUILD_SHARED_LIBS=OFF \
    -DBOX3D_DOUBLE_PRECISION=OFF \
    -DBOX3D_SAMPLES=OFF \
    -DBOX3D_UNIT_TESTS=OFF \
    -DBOX3D_BENCHMARKS=OFF \
    -DBOX3D_DOCS=OFF \
    -DBOX3D_VALIDATE=OFF

cmake --build "$VENDOR/build" --target box3d --parallel

LIB="$(find "$VENDOR/build" -name 'libbox3d.a' -print -quit)"
[ -n "$LIB" ] || { echo "ERROR: libbox3d.a not produced by the build" >&2; exit 1; }
mkdir -p "$OUT"
cp "$LIB" "$OUT/libbox3d.a"
echo "Installed $OUT/libbox3d.a"

# --- layout probe -----------------------------------------------------------
# scripts/abi-types.txt lists one C type per line, optionally followed by a space and a
# comma-separated field list: `b3BodyId index1,world0,generation` (blank lines and # comments
# ignored). Every struct the binding declares in full belongs here; the $assert size pin in
# the split .c3i files must match, and a listed field gets its own offsetof pin.
#
# A type written `b3X=Y` names its C3 spelling outright, for the types whose C3 name the
# prefix-stripping cannot reach: the b3Rec* family is named for the b3::record module, so
# transforming b3RecPlayerInfo would restore the prefix the namespace already carries.
#
# A field written `@name` is one C3 gives no name to — the first arm of an anonymous union, which
# C3 lays out exactly as C does but reports with an empty member name. The offset is probed and
# pinned from the C name as usual; only the name half of the pin is dropped, so the members after
# it keep their positions and their own names.
[ -f "$TYPES" ] || { echo "No $TYPES yet — skipping layout probe."; exit 0; }

PROBE="$VENDOR/build/abi_probe.c"
{
    echo '#include <box3d/box3d.h>'
    echo '#include <stddef.h>'
    echo '#include <stdio.h>'
    echo 'int main(void) {'
    sed -e 's/#.*//' -e '/^[[:space:]]*$/d' "$TYPES" | while IFS= read -r line; do
        tok="${line%% *}"
        t="${tok%%=*}"
        if [ "$tok" = "$line" ]; then
            fields=""
        else
            fields="${line#* }"
        fi
        printf '    printf("%%s %%zu %%zu", "%s", sizeof(%s), _Alignof(%s));\n' "$t" "$t" "$t"
        if [ -n "$fields" ]; then
            saved_ifs="$IFS"
            IFS=,
            for f in $fields; do
                printf '    printf(" %%s=%%zu", "%s", (size_t)offsetof(%s, %s));\n' "$f" "$t" "${f#@}"
            done
            IFS="$saved_ifs"
        fi
        printf '%s\n' '    printf("\n");'
    done
    echo '    return 0;'
    echo '}'
} > "$PROBE"

"${CC:-cc}" -std=c17 -I"$VENDOR/include" "$PROBE" -o "$VENDOR/build/abi_probe"
probed="$("$VENDOR/build/abi_probe")"

case "$MODE" in
    --update)
        printf '%s\n' "$probed" > "$SIZES"
        generate_layout "$probed" > "$LAYOUT"
        echo "Wrote $SIZES and $LAYOUT:"
        printf '%s\n' "$probed"
        ;;
    --check)
        if [ ! -f "$SIZES" ]; then
            echo "ERROR: $SIZES missing. Run: scripts/build-box3d.sh --update" >&2
            exit 1
        fi
        if ! printf '%s\n' "$probed" | diff -u "$SIZES" - ; then
            echo "ERROR: box3d struct layout drifted from $SIZES." >&2
            echo "The \$assert pins in the C3 binding are now wrong. Update both together." >&2
            exit 1
        fi
        if [ ! -f "$LAYOUT" ]; then
            echo "ERROR: $LAYOUT missing. Run: scripts/build-box3d.sh --update" >&2
            exit 1
        fi
        if ! generate_layout "$probed" | diff -u "$LAYOUT" - ; then
            echo "ERROR: $LAYOUT is stale. Regenerate it: scripts/build-box3d.sh --update" >&2
            exit 1
        fi
        echo "Layouts match $SIZES, and $LAYOUT matches the probe."
        ;;
    *)
        printf '%s\n' "$probed"
        ;;
esac
